version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Maven"
      - yum install -y maven
      - echo "Installing Docker..."
      - yum install -y docker
      - service docker start
      - echo "Logging in to Amazon ECR..."
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)

  build:
    commands:
      - echo "Building application"
      - mvn clean package
      - echo "Building Docker image..."
      - docker build -t my-app .
      - echo "Tagging Docker image..."
      - docker tag my-app:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/springboot03ecr:latest
      - echo "Pushing Docker image to ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/springboot03ecr:latest


artifacts:
  files:
    - target/*.jar
