version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo "Installing Maven"
      - yum install -y maven

  build:
    commands:
      - echo "Building application"
      - mvn clean package

artifacts:
  files:
    - target/*.jar
